# Generated by Django 5.2 on 2025-05-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
